CREATE TABLE Office (
    OfficeID INT NOT NULL IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Code NVARCHAR(10) NOT NULL,
    Address NVARCHAR(200) NULL,
    City NVARCHAR(100) NULL,
    Country NVARCHAR(100) NULL,
    CreatedAt DATE NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1,

    CONSTRAINT PK_Office PRIMARY KEY (OfficeID),
    CONSTRAINT UQ_Office_Code UNIQUE (Code),
    CONSTRAINT UQ_Office_Name UNIQUE (Name)
);
