CREATE TABLE SalaryCalcTax (
    SalaryCalcID INT NOT NULL,
    CalcDate DATE NOT NULL,
    TaxID INT NOT NULL,
    AppliedRate DECIMAL(5,4) NOT NULL,
    TaxValue DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_SalaryCalcTax PRIMARY KEY (SalaryCalcID, CalcDate),
    CONSTRAINT FK_SCT_Calc FOREIGN KEY (SalaryCalcID) REFERENCES SalaryCalc(SalaryCalcID) ON DELETE CASCADE,
    CONSTRAINT FK_SCT_Tax FOREIGN KEY (TaxID) REFERENCES Tax(TaxID)
);